import { Game_System } from "../rpg_object/Game_System";
import { Game_Timer } from "../rpg_object/Game_Timer";
import { Game_Switches } from "../rpg_object/Game_Switches";
import { Game_Variables } from "../rpg_object/Game_Variables";
import { Game_SelfSwitches } from "../rpg_object/Game_SelfSwitches";

declare export const $dataActors: RPG.DataActor[];
declare export const $dataClasses: RPG.DataClass[];
declare export const $dataSkills: RPG.DataSkill[];
declare export const $dataItems: RPG.DataItem[];
declare export const $dataWeapons: RPG.DataWeapon[];
declare export const $dataArmors: RPG.DataArmor[];
declare export const $dataEnemies: RPG.DataEnemy[];
declare export const $dataTroops: RPG.DataTroop[];
declare export const dataStates: RPG.DataState[];
declare export const $dataAnimations: RPG.DataAnimation[];
declare export const $dataTilesets: RPG.DataTileset[];
declare export const $dataCommonEvents: RPG.DataCommonEvent[];
declare export const $dataSystem: RPG.DataSystem;
declare export const $dataMapInfos: RPG.DataMapInfo[];
declare export const $dataMap: RPG.DataMap[];
// @todo make sure to declare those variables later
$gameTemp = null;
declare export const $gameSystem: Game_System;
$gameScreen = null;
declare export const $gameTimer: Game_Timer;
declare export const $gameMessage: Game_Message;
declare export const $gameSwitches: Game_Switches;
declare export const $gameVariables: Game_Variables;
declare export const $gameSelfSwitches: Game_SelfSwitches;
$gameActors = null;
$gameParty = null;
$gameTroop = null;
$gameMap = null;
$gamePlayer = null;
$testEvent = null;